# Generated by Django 2.1.2 on 2018-10-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='andrew_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Andrew ID'),
        ),
    ]
